# Generated by Django 5.0.14 on 2026-04-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('OWNER', 'Salon Owner'), ('STAFF', 'Staff Member'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
