# Generated by Django 5.0.14 on 2026-04-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='Monrovia, Liberia', max_length=255),
        ),
    ]
