# Generated by Django 5.2.13 on 2026-05-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('APPROVAL', 'Approval'), ('BOOKING', 'Booking'), ('BILLING', 'Billing'), ('SYSTEM', 'System'), ('BROADCAST', 'Broadcast'), ('PROMOTION', 'Promotion')], default='SYSTEM', max_length=20),
        ),
    ]
