# Generated by Django 5.2.13 on 2026-05-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('OWNERS', 'Salon Owners Only'), ('CUSTOMERS', 'Customers Only')], default='ALL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
