version: '3.8'

services:
  # Backend Services
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-findsalon}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
    networks:
      - findsalon_network

  redis:
    image: redis:7-alpine
    networks:
      - findsalon_network

  backend:
    build: ./backend
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - POSTGRES_DB=${POSTGRES_DB:-findsalon}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
    networks:
      - findsalon_network

  # Frontend Service
  frontend:
    build: ./frontend
    # ports:
    #   - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://72.61.15.24:8090/api}
    depends_on:
      - backend
    networks:
      - findsalon_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./backend/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8090:80"
    depends_on:
      - backend
      - frontend
    networks:
      - findsalon_network

networks:
  findsalon_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
