# Generated by Django 5.0.14 on 2026-04-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicecategory_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='max_staff',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
