# Generated by Django 5.2.13 on 2026-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_adpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='plan',
            field=models.CharField(choices=[('TRIAL', 'Free Trial'), ('STARTER', 'FindSalon Starter'), ('PRO', 'FindSalon Pro')], max_length=20),
        ),
    ]
