# Generated by Django 5.0.14 on 2026-04-24 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        ('services', '0002_servicecategory_service_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff/avatars/')),
                ('availability', models.CharField(choices=[('ON_DUTY', 'On Duty'), ('ON_BREAK', 'On Break'), ('OFF_SHIFT', 'Off Shift')], default='OFF_SHIFT', max_length=20)),
                ('performance_rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_services', models.ManyToManyField(blank=True, related_name='assigned_staff', to='services.service')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='salons.salon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='staff.staffmember')),
            ],
            options={
                'verbose_name_plural': 'Staff Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
