# Generated by Django 5.2.13 on 2026-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_salon_address_alter_salon_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
