# Generated by Django 5.0.14 on 2026-05-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_salon_is_active_salon_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='subscription_plan',
            field=models.CharField(choices=[('TRIAL', 'Free Trial'), ('ESSENTIAL', 'Essential'), ('ELITE', 'Elite')], default='TRIAL', max_length=20),
        ),
    ]
