# Generated by Django 5.2.13 on 2026-05-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_salon_subscription_expiry_salon_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='offers_home_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='salon_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical Salon'), ('INDEPENDENT', 'Independent Pro (Home Service)')], default='PHYSICAL', max_length=20),
        ),
    ]
