# Generated by Django 5.2.13 on 2026-05-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_salon_offers_home_service_salon_salon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salon',
            name='require_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
