# Generated by Django 5.2.13 on 2026-05-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_salon_deposit_amount_salon_require_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
