# Generated by Django 5.2.13 on 2026-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0010_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='subscription_plan',
            field=models.CharField(choices=[('TRIAL', 'Free Trial'), ('STARTER', 'FindSalon Starter'), ('PRO', 'FindSalon Pro')], default='TRIAL', max_length=20),
        ),
    ]
