# Generated by Django 5.2.13 on 2026-05-04 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0006_salon_subscription_expiry_salon_subscription_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(help_text='Upload ad banner', upload_to='ads/')),
                ('link_url', models.URLField(blank=True, help_text='Where the ad leads to (defaults to salon page)')),
                ('placement', models.CharField(choices=[('LANDING_PAGE', 'Landing Page Hero'), ('BOOKING_PAGE', 'Salon Booking Sidebar'), ('CLIENT_DASHBOARD', 'Client Dashboard Banner')], default='LANDING_PAGE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='salons.salon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
